### ISSUE TITLE
Cannot edit Catalog

### ISSUE THREAD

**Issue by dglemos** [ejp-rd-vp/FDP-Reference-Implementation-Configuration#4]
While following [these instructions to create a new record](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration#create-a-new-record---a-data-service-that-does-visualization-box-whisker-plot) I got a problem when editing a Catalog or even trying to remove it.

If I try to edit any information in the Catalog I get the following error message: "Unable to update entity data"
Now I have a draft Catalog that I want to edit or delete but I cannot do any of those actions.

![Screenshot 2024-01-22 at 17 14 45](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration/assets/44366649/fdd43e59-93cd-42eb-8129-97b8165e44f0)

**Comment by dglemos** [comment]
I also can't update My FAIR Data Point info.

![Screenshot 2024-01-23 at 09 23 40](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration/assets/44366649/b1e20ac1-bdcc-46d9-99d3-475f56cb32eb)

**Comment by markwilkinson** [comment]
answered in the FiaB repo
