### ISSUE TITLE
Handling duplicate entries in the VP Index

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/FDP-Reference-Implementation-Configuration#5]
Raising this issue on behalf of the VP Portal development team:
- The list of resources in the VP Index have duplicate entries, and there is no current tool to flag them.
- The portal retrieves the information from the sparql endpoint (https://graphdb.ejprd.semlab-leiden.nl/repositories/vp-index )
- See image for example
![MicrosoftTeams-image (10)](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration/assets/91144909/0a164f52-2bd0-4603-84f1-f80d00300cec)

**Comment by markwilkinson** [comment]
This is not related to FDP configuration.

Please re-post as an issue to the FAIR Data Point project:  https://github.com/FAIRDataTeam/FAIRDataPoint
